54397/retrieve list of leads
FJala-Tr2020/front-end-e1 pull request #5
Opened 2021-07-20 13:25 UTC by LuosNahim

Main Change: Change from xhttp to axios to be the rest client 
Added: ILead interface

2021-07-20 22:33 UTC, douglasalizares commented on src/index.html
> +        <a class="nav-link " id='leadLink' aria-current="page" href='#' onclick="ClickVersion()">Version</a>
we are using MVVM, we should use the events as specified by the framework. 
https://angular.io/guide/event-binding

2021-07-20 22:43 UTC, douglasalizares commented on src/pages/leadTable.ts
> +            axios.get('http://localhost:3000/leads').then(({ data }) => {
using localhost limits the operation of the project, if the endpoint is running on a local server.
We could make use of environment variables.  https://webpack.js.org/guides/environment-variables/

2021-07-22 15:15 UTC, marcelo-yourday requested changes

2021-07-22 15:15 UTC, marcelo-yourday commented on src/index.ts
> +  registros = [
I don't see we are using this data in any place, please review if those are needed.

2021-07-22 15:15 UTC, marcelo-yourday commented on src/index.html
> +  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
It would be great if we were able to create a component for the NavBar, anyways, we can push this code.

2021-07-22 15:15 UTC, marcelo-yourday commented on src/pages/leadTable.spec.ts
> +const mockLead:ILead = {
I'm not sure if this test have any sense. Please take a look.

2021-07-23 03:49 UTC, LuosNahim commented
The observations were modified, please take a look of the new pull request.
Best Regards.

2021-07-23 14:24 UTC, marcelo-yourday approved these changes

2021-07-23 21:50 UTC, merged