Refactoring Modal window (I've dropped by mistake)
FJala-Tr2020/front-end-e1 pull request #6
Opened 2021-07-24 21:32 UTC by LuosNahim

Please take a look on this  Pull request.
Some conflicts were reported with the modal ,
I've realized that I dropped by mistake.

2021-07-26 07:04 UTC, DianaVargasOrellana approved these changes

2021-07-27 01:01 UTC, eencinasq requested changes

2021-07-27 01:01 UTC, eencinasq commented on src/components/ModalVersion.html
> +        <h5 class="modal-title" id="exampleModalLabel">CMS Eq.1 Version</h5>
Modal label should be in the ViewModel.

2021-07-27 01:01 UTC, eencinasq commented on src/components/Navbar.html
> +      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
Navbar should be extensible.
`
<navbar params:'listitems:'> </navbar>
`

2021-07-30 21:39 UTC, LuosNahim commented
Please, check this new pull request, 
I've noticed that the coverage is less than the expected, 
Most of them are from the viewModel components as the modal and the router.
Best Regards

2021-07-31 00:54 UTC, eencinasq approved these changes

2021-07-31 00:55 UTC, merged